XTraTech/XTraTechWeb/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using XTraTech.Entities.COM;
using XTraTech.Helper;
using XTraTechWeb.Models;

namespace XTraTechWeb.Controllers
{
    public class RegistrationController : Controller
    {
        //
        // GET: /Registration/

        public ActionResult Index(string ClientId)
        {
            if (Session["LoggedInUser"] != null)
            {
                Client client = new Client();
                client.Load(Convert.ToInt16(ClientId), true);
                Registration reg = new Registration();
                
                return View(reg);
            }
            else
            {
                return base.RedirectToAction("Index", "Login");
            }
        }

        //
        // POST: /Registration/

        [HttpPost]
        public ActionResult Index(Registration model)
        {
            Client client = new Client();
            List<Staff> staffs = new List<Staff>();
            Staff staff = new Staff();

            try
            {
                if (Session["LoggedInUser"] != null)
                {
                    client.Address1 = model.Address1;
                    client.Address2 = model.Address2;
                    client.City = model.City;
                    client.CompanyName = model.CompanyName;
                    client.Country = model.Country;
                    client.Email = model.Email;
                    client.FirstName = model.FirstName;
                    client.LastName = model.LastName;
                    client.MemberOf = model.MemberOf;
                    client.PhoneNumber = model.PhoneNumber;
                    client.State = model.State;
                    client.ZIP = model.ZIP;

                    client.UseDefaultSMTP = model.usedefautSMTP;
                    client.SMTPAddress = model.SMTPAddress;
                    client.PortNumber = model.PortNumber;
                    client.EnableSSL = model.enableSSL;
                    client.FromEmail = model.FromEmail;
                    client.EmailPassword = model.EmailPwd;

                    staff.Email = model.Email;
                    staff.FirstName = model.FirstName;
                    staff.LastName = model.LastName;
                    staff.Password = model.Password;
                    staff.PhoneNumber = model.PhoneNumber;
                    staff.UserName = model.UserName;
                    staffs.Add(staff);
                    client.Staffs = staffs;

                    client.Save();

                    //Email Here.
                    Email email = new Email();
                    email.emailTo = model.Email;
                    email.RunInBackground = true;
                    email.subject = "Account Registration Success";

                    StringBuilder sb = new StringBuilder();
                    sb.Append("<h1> Hi, " + model.LastName + " " + model.FirstName + "</h1>");
                    sb.Append("<p>Your Registration is success and now you can use the worlds most powerfull reservation engine</p>");
                    sb.Append("<br/><br/>");
                    sb.Append("<h3>Your login details are here:</h3>");
                    sb.Append("<p>UserName: " + model.UserName + "</p>");
                    sb.Append("<p>Password: " + model.Password + "</p>");

                    email.body = sb.ToString();
                    email.Send();
                }
                else
                {
                    return base.RedirectToAction("Index", "Login");
                }
            }
            catch (Exception)
            {
                return base.RedirectToAction("ErrorPage", "Comman");
            }
            return RedirectToAction("RegistrationSuccess", new { Success = true });
        }

        public ActionResult RegistrationSuccess(bool Success)
        {
            ViewBag.Success = Success;
            return View();
        }
    }
}

XTraTech/XTraTechWeb/Views/Administration/ViewClientDetails.cshtml
@model XTraTechWeb.Models.clientmodel
@{
    ViewBag.Title = "ViewClientDetails";
}

<section id="content">
    <div class="container flight-detail-page">
        <div class="row">
            <div id="main" class="col-md-12">
                <div class="booking-section BookeTickets-box">
                    <div class="person-information">
                        <h2>Client Details</h2>
                        <hr />
                        @if (string.IsNullOrEmpty(Model.Client.ZIP))
                        {
                            <div class="row">
                                <div class="col-sms-12 col-md-12">
                                    <div class="alert alert-notice">
                                        This client profile is not complete. Please  @Html.ActionLink(" CLICK HERE ", "Index", "Registration", new { ClientId = ViewBag.ClientId }, new { @class = "skin-color" }) to complete client profile details!..
                                        <span class="close"></span>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="row">
                                <div class="col-md-6">
                                    <dl class="term-description">
                                        <dt>Client Name</dt>
                                        <dd>@Model.Client.FirstName @Model.Client.LastName</dd>
                                        <dt>Member Of</dt>
                                        <dd>@Model.Client.MemberOf</dd>
                                        <dt>Country</dt>
                                        <dd>@Model.Client.Country</dd>
                                        <dt>City</dt>
                                        <dd>@Model.Client.City</dd>
                                        <dt>State</dt>
                                        <dd>@Model.Client.State</dd>
                                        <dt>ZIP</dt>
                                        <dd>@Model.Client.ZIP</dd>
                                    </dl>
                                </div>
                                <div class="col-md-6">
                                    <dl class="term-description">
                                        <dt>Company Name</dt>
                                        <dd>@Model.Client.CompanyName</dd>
                                        <dt>Email</dt>
                                        <dd>@Model.Client.Email</dd>
                                        <dt>Phone</dt>
                                        <dd>@Model.Client.PhoneNumber</dd>
                                        <dt>Joined On</dt>
                                        <dd>@Model.Client.CreatedOn</dd>
                                        <dt>Address1</dt>
                                        <dd>@Model.Client.Address1</dd>
                                        <dt>Address2</dt>
                                        <dd>@Model.Client.Address2</dd>
                                    </dl>
                                </div>
                            </div>
                            <h4>Email Credentials</h4>
                            <hr />
                            <div class="row">
                                <div class="col-md-6">
                                    <dl class="term-description">
                                        <dt>Use Default SMTP</dt>
                                        <dd>@Model.Client.UseDefaultSMTP</dd>
                                        <dt>SMTP Address</dt>
                                        <dd>@Model.Client.SMTPAddress</dd>
                                        <dt>Port Number</dt>
                                        <dd>@Model.Client.PortNumber</dd>
                                    </dl>
                                </div>
                                <div class="col-md-6">
                                    <dl class="term-description">
                                        <dt>Enable SSL</dt>
                                        <dd>@Model.Client.EnableSSL</dd>
                                        <dt>From Email</dt>
                                        <dd>@Model.Client.FromEmail</dd>
                                        <dt>Email Password</dt>
                                        <dd>@Model.Client.EmailPassword</dd>
                                    </dl>
                                </div>
                            </div>
                            <h4>Staffs List</h4>
                            <hr />
                            <table class="table table-bordered table-condensed" align="center">
                                <thead>
                                    <tr class="info">
                                        <th>Staff ID</th>
                                        <th>Name</th>
                                        <th>User ID</th>
                                        <th>Email ID</th>
                                        <th>Phone Number</th>
                                        <th>Created On</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int i = 0, j = 1; i < Model.Client.Staffs.Count; i++, j++)
                                    {
                                        <tr>
                                            <td>@Model.Client.Staffs[i].StaffID</td>
                                            <td>@Model.Client.Staffs[i].FirstName @Model.Client.Staffs[i].LastName</td>
                                            <td>@Model.Client.Staffs[i].UserName</td>
                                            <td>@Model.Client.Staffs[i].Email</td>
                                            <td>@Model.Client.Staffs[i].PhoneNumber</td>
                                            <td>@Model.Client.Staffs[i].CreatedOn</td>
                                            
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

XTraTech/XTraTechWeb/Views/Administration/ViewClients.cshtml
@model XTraTechWeb.Models.clientmodel
@{
    ViewBag.Title = "ViewClients";
}

<section id="content">
    <div class="container flight-detail-page">
        <div class="row">
            <div id="main" class="col-md-12">
                <div class="booking-section BookeTickets-box">
                    <div class="person-information">
                        <h2>Clients List</h2>
                        <hr />
                        <table class="table table-bordered table-condensed" align="center">
                            <thead>
                                <tr class="info">
                                    <th>Client ID</th>
                                    <th>Name</th>
                                    <th>Company Name</th>
                                    <th>Country</th>
                                    <th>Email ID</th>
                                    <th>Phone Number</th>
                                    <th>Is Profile Complete</th>
                                    <th>Joined On</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0, j = 1; i < Model.ListofClients.Count; i++, j++)
                                {
                                    <tr>
                                        <td>@Model.ListofClients[i].ClintID</td>
                                        <td>@Model.ListofClients[i].FirstName @Model.ListofClients[i].LastName</td>
                                        <td>@Model.ListofClients[i].CompanyName</td>
                                        <td>@Model.ListofClients[i].Country</td>
                                        <td>@Model.ListofClients[i].Email</td>
                                        <td>@Model.ListofClients[i].PhoneNumber</td>
                                        @if (string.IsNullOrEmpty(Model.ListofClients[i].ZIP))
                                        {
                                            <td>No</td>
                                        }
                                        else
                                        {
                                            <td>Yes</td>
                                        }
                                        <td>@Model.ListofClients[i].CreatedOn</td>
                                        <td><a href="#">@Html.ActionLink("View Details", "ViewClientDetails", "Administration", new { ClientID = Model.ListofClients[i].ClintID }, new { @class = "skin-color" })</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>